import Link from "next/link";
import { ArrowDown, ArrowUpRight } from "lucide-react";
import { ScrollReveal, StaggerChildren } from "../../components/Motion";
import { Kicker } from "../../components/Section";

const beliefs = ["Great businesses begin with uncomfortable questions.", "Capital matters. Conviction matters more.", "Founders don't need another audience. They need the right partner."];
const stages = ["IDEA", "VALIDATION", "INCUBATION", "INVESTMENT", "GROWTH"];

export default function About() { return <main className="editorial-page"><section className="cinema-hero"><Kicker>ABOUT THE FUND · 01</Kicker><h1>We back the people<br />building <em>what comes next.</em></h1><p className="hero-copy">Prabidhi Uthaan Innovation Fund exists to help ambitious ideas move from possibility to reality.</p><div className="hero-scroll"><span>Scroll to explore</span><ArrowDown size={16} /></div></section><section className="dark-band"><div className="wide-copy"><Kicker>01 — WHY WE EXIST</Kicker><ScrollReveal><h2>There is a gap between a good idea and a business that can endure. <em>We work in that gap.</em></h2></ScrollReveal><p>We bring early conviction, practical operating support, and patient alignment to founders who are ready to turn a sharp insight into something real.</p></div></section><section className="beliefs section-shell"><div className="section-inner split-heading"><Kicker>02 — WHAT WE BELIEVE</Kicker><h2>Point of view<br /><em>over noise.</em></h2></div><StaggerChildren className="belief-list">{beliefs.map((belief, index) => <ScrollReveal key={belief} delay={index * 100}><div className="belief-item"><span>0{index + 1}</span><h3>{belief}</h3></div></ScrollReveal>)}</StaggerChildren></section><section className="role-section section-shell"><div className="section-inner"><Kicker>03 — OUR ROLE</Kicker><h2 className="section-title">From first question<br />to <em>lasting company.</em></h2><div className="stage-line">{stages.map((stage, index) => <div className="stage" key={stage}><span>{String(index + 1).padStart(2, "0")}</span><strong>{stage}</strong>{index < stages.length - 1 && <i>↓</i>}</div>)}</div></div></section><section className="full-statement"><Kicker>04 — THE BIGGER PICTURE</Kicker><h2>We want to help build businesses that outlive their first round of funding.</h2></section><section className="closing-cta"><Kicker>05 — START HERE</Kicker><h2>Have something<br /><em>worth building?</em></h2><Link className="button" href="/pitch">Pitch your idea <ArrowUpRight size={18} /></Link></section></main>; }
