"use client";

import { useEffect, useState } from "react";
import { ArrowDown } from "lucide-react";
import { Kicker } from "../../components/Section";
import { ScrollReveal } from "../../components/Motion";

const principles = [["VISION", "Does the founder see something others don't?", "The strongest companies begin with a perspective that feels obvious only after someone has seen it."], ["PROBLEM", "Is the problem real and meaningful?", "We look for friction with consequence, not convenience dressed up as a market."], ["SOLUTION", "Is the proposed solution genuinely useful?", "Useful beats impressive. We care about what people return to, pay for, and share."], ["MARKET", "Can this become a meaningful business?", "A sharp wedge can become a large opportunity when the founder understands the terrain."], ["EXECUTION", "Can the team actually build it?", "Taste, pace, resilience, and the willingness to do the unglamorous work matter."], ["POTENTIAL", "Can the company grow beyond its first market?", "We back businesses with room to compound: in reach, relevance, and value." ]];

export default function Approach() { const [active, setActive] = useState(0); useEffect(() => { const elements = Array.from(document.querySelectorAll<HTMLElement>("[data-principle]")); const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) setActive(Number((entry.target as HTMLElement).dataset.principle)); }), { rootMargin: "-35% 0px -45%" }); elements.forEach(element => observer.observe(element)); return () => observer.disconnect(); }, []); return <main className="approach-page"><section className="approach-intro"><Kicker>THE INVESTMENT FILTER</Kicker><h1>How<br /><em>we think.</em></h1><p>Good judgment is less about having all the answers and more about asking the questions that reveal what matters.</p><ArrowDown className="intro-arrow" /></section><div className="approach-layout"><aside className="approach-index"><span>0{active + 1}</span><div className="approach-progress"><i style={{ transform: `scaleY(${(active + 1) / principles.length})` }} /></div><span>0{principles.length}</span></aside><section className="principle-stack">{principles.map(([label, title, detail], index) => <article data-principle={index} className={`principle ${active === index ? "is-active" : ""}`} key={label}><div className="principle-label"><span>0{index + 1}</span><small>{label}</small></div><ScrollReveal><h2>{title}</h2><p>{detail}</p></ScrollReveal></article>)}</section></div></main>; }
